### ISSUE TITLE
Release里面啥也没有阿，就是空的，aidb库也不能clone了，说大文件配额超了

### ISSUE THREAD

**Issue by garbe-github-support** [TalkUHulk/aidb_android_demo#3]
![image](https://github.com/TalkUHulk/aidb_android_demo/assets/131808107/a97c5bb9-ea90-49c7-8d49-914a1c4cd680)
![image](https://github.com/TalkUHulk/aidb_android_demo/assets/131808107/ff8838ba-8437-4e93-9612-8188398fb969)

Unpacking objects: 100% (4/4), 618 bytes | 30.00 KiB/s, done.
From https://github.com/TalkUHulk/ai.deploy.box
 * branch            5b613d13e8e21b47c15499cd173b323c750f614d -> FETCH_HEAD
Downloading sample-wasm/models/ch_ppocr_det_v3.id.h (13 KB)
Error downloading object: sample-wasm/models/ch_ppocr_det_v3.id.h (84a04e7): Smudge error: Error downloading sample-wasm/models/ch_ppocr_det_v3.id.h (84a04e73d4966a1a88bda6abfe9fb6f286d601abd63586e0f65ebbda695b52dc): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to 'D:\ML_Android\aidb_android_demo\.git\modules\aidb\src\main\cpp\lfs\logs\20230927T162845.3459204.log'.
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: sample-wasm/models/ch_ppocr_det_v3.id.h: smudge filter lfs failed
fatal: Unable to checkout '5b613d13e8e21b47c15499cd173b323c750f614d' in submodule path 'aidb/src/main/cpp'
![image](https://github.com/TalkUHulk/aidb_android_demo/assets/131808107/ff62a5b8-42b7-45ff-af63-eb3cc8003cbe)

**Comment by TalkUHulk** [comment]
直接下载zip包吧，免费

**Comment by TalkUHulk** [comment]
后面我会把大文件单独拎出来放到别的地方

**Comment by TalkUHulk** [comment]
> ![image](https://user-images.githubusercontent.com/131808107/270916423-a97c5bb9-ea90-49c7-8d49-914a1c4cd680.png) ![image](https://user-images.githubusercontent.com/131808107/270916459-ff8838ba-8437-4e93-9612-8188398fb969.png)
> 
> Unpacking objects: 100% (4/4), 618 bytes | 30.00 KiB/s, done. From https://github.com/TalkUHulk/ai.deploy.box
> 
> * branch            5b613d13e8e21b47c15499cd173b323c750f614d -> FETCH_HEAD
>   Downloading sample-wasm/models/ch_ppocr_det_v3.id.h (13 KB)
>   Error downloading object: sample-wasm/models/ch_ppocr_det_v3.id.h (84a04e7): Smudge error: Error downloading sample-wasm/models/ch_ppocr_det_v3.id.h (84a04e73d4966a1a88bda6abfe9fb6f286d601abd63586e0f65ebbda695b52dc): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
> 
> Errors logged to 'D:\ML_Android\aidb_android_demo.git\modules\aidb\src\main\cpp\lfs\logs\20230927T162845.3459204.log'. Use `git lfs logs last` to view the log. error: external filter 'git-lfs filter-process' failed fatal: sample-wasm/models/ch_ppocr_det_v3.id.h: smudge filter lfs failed fatal: Unable to checkout '5b613d13e8e21b47c15499cd173b323c750f614d' in submodule path 'aidb/src/main/cpp' ![image](https://user-images.githubusercontent.com/131808107/270916737-ff62a5b8-42b7-45ff-af63-eb3cc8003cbe.png)

关于Release页面问题，上次修改后忘记发布了。现在应该有了

**Comment by TalkUHulk** [comment]
> 好的 非常感谢 可以放个二维码开个赞助 俺赞助 哈哈哈

感谢老铁
